services:
  mssql:
    container_name: sqlServerApi
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "ApiNet.2024!"
    ports:
      - 31000:1433